apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: aks-cluster-rg
spec:
  forProvider:
    location: "canadacentral"
---
apiVersion:  network.azure.upbound.io/v1beta1
kind: VirtualNetwork
metadata:
  name: aks-cluster-vnet
spec:
  forProvider:
    resourceGroupName: aks-cluster-rg
    location: "canadacentral"
    addressSpace: 
      - "10.0.0.0/16"
---
apiVersion: network.azure.upbound.io/v1beta1
kind: Subnet
metadata:
  name: aks-cluster-private-subnet
spec:
  forProvider:
    resourceGroupName: aks-cluster-rg
    virtualNetworkName: aks-cluster-vnet
    addressPrefixes: 
      - "10.0.1.0/24"
    enforcePrivateLinkServiceNetworkPolicies: false
---
apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  name: aks-cluster
spec:
  forProvider:
    resourceGroupName: aks-cluster-rg
    location: "canadacentral"
    dnsPrefix: "aks-cluster-dns"
    privateClusterEnabled: false
    privateClusterPublicFqdnEnabled: true
    defaultNodePool:
      - name: "workload"
        vmSize: "Standard_B2s"
        nodeCount: 1
        upgradeSettings:
          - maxSurge: 10%
        vnetSubnetId: "/subscriptions/{subscription-id}/resourceGroups/aks-cluster-rg/providers/Microsoft.Network/virtualNetworks/aks-cluster-vnet/subnets/aks-cluster-private-subnet"
        spotMaxPrice: -1 
